steps:
  # Build the manager image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGISTRY}/wp-ai-wp-manager:${_TAG}',
      '-f', 'Dockerfile.manager',
      '.'
    ]

  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGISTRY}/wp-ai-wp-manager:${_TAG}']

substitutions:
  _REGISTRY: 'docker.io/library'  # Default registry
  _TAG: 'latest'                  # Default tag

options:
  machineType: 'N1_HIGHCPU_8' 