services:
  wp-manager:
    image: ${REGISTRY:-docker.io/library}/wp-ai-wp-manager:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.manager
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - type: bind
        source: ./wp-sites
        target: /var/www/sites
      - type: bind
        source: ./wp-shared
        target: /var/www/shared
    ports:
      - "${WP_PORT:-8080}:80"
      - "${MYSQL_PORT:-3307}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secure_root_password
      - MYSQL_COMMON_USER=wp_user
      - MYSQL_COMMON_PASSWORD=wp_password
      - WP_PORT=${WP_PORT:-8080}
    privileged: true
    working_dir: /app
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    command: ["tail", "-f", "/dev/null"] 