services:
  wp-manager:
    image: ${REGISTRY:-docker.io/library}/wp-ai-wp-manager:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.manager
    volumes:
      - type: npipe
        source: \\.\pipe\docker_engine
        target: /var/run/docker.sock
      - type: bind
        source: ./wp-sites
        target: /var/www/sites
    ports:
      - "8000:80"
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secure_root_password
      - MYSQL_COMMON_USER=wp_user
      - MYSQL_COMMON_PASSWORD=wp_password
    privileged: true
    working_dir: /app
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    command: ["apache2-foreground"]  # Changed this 